name: Push

on:
  push:
    branches:
      - main
env:
  DOCKER_FILE_PATH: Dockerfile
  GOLANG_VERSION: 1.19

jobs:
  build:
    name: Build
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GOLANG_VERSION }}

    # Setting up helm binary
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.8.2

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        only-new-issues: false
        args: --timeout 10m

    # Run Tests
    - name: Test
      run: make test

    - name: Generate Tag
      id: generate_tag
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
        RELEASE_BRANCHES: main
        DRY_RUN: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ${{ env.DOCKER_FILE_PATH  }}
        push: true
        tags: |
          ${{ github.actor }}/install-plan-approver-operator:${{ steps.generate_tag.outputs.new_tag }}
        labels: |
          org.opencontainers.image.source=${{ github.event.repository.clone_url }}
          org.opencontainers.image.created=${{ steps.prep.outputs.created }}

    - name: Update Version
      env:
        VERSION: ${{ steps.generate_tag.outputs.new_tag }}
      run: make bump-version

    # Commit back changes
    - name: Commit files
      run: |
        git config --local user.email "github-root@stakater.com"
        git config --local user.name "stakater-github-root"
        git status
        git add .
        git commit -m "[skip-ci] Update artifacts" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
        branch: main

    - name: Comment on PR
      uses: mshick/add-pr-comment@v2
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        message-success: '@${{ github.actor }} Image is available for testing. `docker pull ${{ github.repository }}:${{ steps.generate_tag.outputs.GIT_TAG }}`'
        message-failure	: '@${{ github.actor }} Yikes! You better fix it before anyone else finds out! [Build](https://github.com/${{ github.repository }}/commit/${{ github.event.pull_request.head.sha }}/checks) has Failed!'
        allow-repeats: true
